name: ETL Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
 id-token: write  

jobs:
  test-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias para pruebas
        run: |
          python3 -m venv env-test
          source env-test/bin/activate
          pip install --upgrade pip
          pip install numpy==1.23.5 pandas==1.5.3 pyarrow==12.0.0 pytest==7.4.0 holidays==0.26 boto3==1.28.0

      - name: Ejecutar pruebas de ETL
        run: |
          source env-test/bin/activate
          pytest tests/ -v

  run-etl-and-upload:
    runs-on: ubuntu-latest
    needs: test-etl
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Configurar credenciales AWS y asumir el rol LabRole
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::848073509548:role/LabRole
          role-duration-seconds: 3600

      - name: Instalar dependencias para ETL
        run: |
          python3 -m venv env-etl
          source env-etl/bin/activate
          pip install --upgrade pip
          pip install numpy==1.23.5 pandas==1.5.3 pyarrow==12.0.0 boto3==1.28.0 holidays==0.26

      - name: Ejecutar ETL y subir archivos a S3
        run: |
          source env-etl/bin/activate
          echo "🔍 Verificando acceso a S3..."
          aws sts get-caller-identity
          echo "📤 Ejecutando ETL para Dim_Customer..."
          python scripts/dim_customer.py || { echo "Error al ejecutar dim_customer.py"; exit 1; }
          echo "📤 Ejecutando ETL para Dim_Date..."
          python scripts/dim_date.py || { echo "Error al ejecutar dim_date.py"; exit 1; }
          echo "📤 Ejecutando ETL para Dim_Film..."
          python scripts/dim_film.py || { echo "Error al ejecutar dim_film.py"; exit 1; }
          echo "📤 Ejecutando ETL para Dim_Store..."
          python scripts/dim_store.py || { echo "Error al ejecutar dim_store.py"; exit 1; }

  deploy-scripts:
    runs-on: ubuntu-latest
    needs: run-etl-and-upload
    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciales AWS y asumir el rol LabRole
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::<TU_CUENTA_AWS_ID>:role/LabRole
          role-duration-seconds: 3600

      - name: Subir scripts a S3 para Glue
        run: |
          echo "📤 Subiendo scripts a S3..."
          aws s3 cp scripts/dim_customer.py s3://cmjm_datalake/scripts_glue2/dim_customer.py --region us-east-1 --acl bucket-owner-full-control
          aws s3 cp scripts/dim_date.py s3://cmjm_datalake/scripts_glue2/dim_date.py --region us-east-1 --acl bucket-owner-full-control
          aws s3 cp scripts/dim_film.py s3://cmjm_datalake/scripts_glue2/dim_film.py --region us-east-1 --acl bucket-owner-full-control
          aws s3 cp scripts/dim_store.py s3://cmjm_datalake/scripts_glue2/dim_store.py --region us-east-1 --acl bucket-owner-full-control
          echo "Scripts subidos correctamente a S3"
